### ISSUE TITLE
FiveSafes.Net Package/push to nuget

### ISSUE THREAD

**Issue by dcl10** [Health-Informatics-UoN/FiveSafes.Net#1]
## Description
FiveSafes.Net code is used in a few projects now. It needs to be separated into its own repo and packaged up on nuget.

## Tasks
- [X] Create FiveSafes.Net repo
- [x] Add src and tests
- [x] Add workflows
  - [x] build and test workflows
  - [x] publish to nuget workflow
- [x] Publish to nuget
